source = ~/.config/hypr/noctalia.conf

general {
    grace = 5
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 1.3
    brightness = 0.8
    vibrancy = 0.21
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $primary
    inner_color = $surface_variant
    font_color = $on_surface_variant
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 8
    check_color = $secondary
    fail_color = $error
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $tertiary
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 80
    font_family = JetBrainsMono Nerd Font
    color = $primary
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    color = $on_surface_variant
    position = 0, 20
    halign = center
    valign = center
}
