# Configuration for sops secret encryption
keys:
  - &host_bebra_pc age1chsja2y7mqcs8ppvgp4g9skdv5sv8akn3v88qwlru8h9r60mesmskkh46n
  - &user_bebra_pc age1sm5eetfqygn3turqq8l0r2nz9ph6tvupja475j59dv6qsngpavcsps8u96
  - &server_fvds age1h2z2clkftyxwz3pjm5m2986506p07e32pjt2exksqyv0dem7ja4sa6v2um
creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *host_bebra_pc
          - *user_bebra_pc
          - *server_fvds

