# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b142d013-95df-45e3-bd4d-c001bbb0f039";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b142d013-95df-45e3-bd4d-c001bbb0f039";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b142d013-95df-45e3-bd4d-c001bbb0f039";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A054-7B52";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/dd52490b-72c8-4c82-9b5f-85264848ed2e";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/6f630c04-fc94-4df5-bbbe-1d803c6fed4d";
      fsType = "btrfs";
      options = [ "compress=zstd" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8dea6f53-8bf2-4afc-9cb8-b673b74f44eb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
